# Generated by Django 3.0.7 on 2020-06-26 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=100)),
                ('food_type', models.CharField(choices=[('BR', 'Bữa sáng'), ('LU', 'Bữa trưa'), ('DI', 'Bữa tối'), ('BE', 'Đồ uống'), ('SN', 'Ăn vặt')], default='SN', max_length=2)),
                ('description', models.TextField()),
                ('price', models.FloatField(default=0)),
                ('discount', models.FloatField(default=0)),
                ('img', models.ImageField(upload_to='static/images/foods')),
            ],
        ),
    ]
